Dev orm nikolaev
abramson21/ORMLibrary pull request #5
Opened 2020-11-18 13:20 UTC by abramson21

Работают маппинги между таблицами "Author" и "Book".

2020-11-23 21:24 UTC, Const-Phi requested changes
В целом неплохо, но есть ряд нюансов. Я о них написал. К тому же, вероятно, стоит детально проговорить предметную область &ndash; возможно, организуем созвон или доживём до среды (25.11.2020).

2020-11-23 21:24 UTC, Const-Phi commented on Library.Domain/Group.cs
> +    public class Group
А для чего предназначена данная сущность? `Group` &ndash; группа чего? Объединение авторов и книг в какую-то третью сущность, смысл которой от меня ускользает. Можно чуть больше подробностей?

2020-11-23 21:24 UTC, Const-Phi commented on Library.Domain/Name.cs
> +
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) Обычно атрибут, навешиваемый на метод, свойство, поле etc, не отделяется пустой строкой от своей цели (метода, свойства, поля etc).

2020-11-23 21:24 UTC, Const-Phi commented on Library.Domain/Name.cs
> +            if (value != null && string.IsNullOrWhiteSpace(value))
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) Метод [`string.IsNullOrWhiteSpace`](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=net-5.0) и так проверяет свой параметр на `null`:
> Indicates whether a specified string is null, empty, or consists only of white-space characters.

---
**UPD**
Понял, что не прав, и в проверке не про это. Но не согласен с частью предиката `value != null` &ndash; если `value == null`, то всё OK?

2020-11-23 21:24 UTC, Const-Phi commented on Library.Domain/Name.cs
> +            return HashCode.Combine(this.FirstName, this.SecondName, this.MiddleName ?? string.Empty);
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) `MiddleName`, исходя из остального кода, ни коим образом не отличается от `FirstName` и `LastName`, а значит, либо все три свойства могут быть `null` (что вероятнее, с учётом вашей проверки в `CheckInputString`), либо все три не могут. Странно выделять такую особенность поведения. Скорее всего рудемент, оставшийся от `nullable` `MiddleName`.

2020-11-23 21:24 UTC, Const-Phi commented on Infrastructure/Infrastructure.csproj
> +  </ItemGroup>
**Out of scope:** StyleCop сюда тоже неплохо бы добавить 😄

2020-11-23 21:24 UTC, Const-Phi commented on TestORMLibrary/App.cs
> +                Console.WriteLine("_________________________________________");
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#:~:text=Reviewers%20should%20always%20feel%20free,they%20could%20choose%20to%20ignore.) Можно было воспользоваться перегрузкой конструктора строки:
```cs
// выводим строку из 42 минусов/дефисов
Console.WriteLine(new string('-', 42)); 
```

2020-11-27 07:40 UTC, abramson21 commented on Library.Domain/Group.cs
> +    public class Group
Разобрался, сущность не нужна.

2020-11-27 07:52 UTC, closed without merging

2020-11-27 07:52 UTC, abramson21 commented
Решено