Обновлена база данных
abramson21/ORMLibrary pull request #8
Opened 2020-12-09 18:04 UTC by abramson21

Рабочая версия базы данных для маппингов [devORM_nikolaev](https://github.com/abramson21/ORMLibrary/tree/devORM_nikolaev).
Добавлены .sql и .bak

2020-12-10 20:09 UTC, Const-Phi requested changes
#  🔥 **ВАЖНО** 🔥
Мной был выполнен `rebase` на `master`. Это обусловлено попыткой уменьшить уровень информационного шума, так как вкладка `Files changed` (в основном используемая в процессе рецензирования кода) строит `diff` (разницу / рассогласование) по двум веткам целевой, то есть той, _в которую_ будут внесены изменения (в нашем случае `master`) и текущей (в нашем случае `devSQL_nikolaev`). Данный факт означает следующие трудности для вас.

## 🛠️ Необходимые шаги 
 Прежде чем выполнить `push` в данную ветку коммитов Вам НЕОБХОДИМО выполнить `pull` (`rebase` или  `merge` уже не суть важно) и  разрешить возможные конфликты слияния. При необходимости обратиться ко мне (даже если просто есть сомнения). Прежде чем экспериментировать лучше сделать копию локальной ветки.

## 📂  Остальные изменения
Ещё одно существенное изменение &ndash; структура каталогов для организации хранения всякого. Я выкинул странный файл `devER_Alekseev` (я не понял его смысла &ndash; файл с переводом строки и всё). Не знаю зачем вы храните `.bak` в репозитории, но я оставил его, переложив в папку `scripts`, хоть она нацелена в первую очередь на организацию хранения SQL-скриптов.

Код планируется хранить в папке `source`, а документацию &ndash; в `documentation`.

## 💻  Что нужно изменить Вам
Возвращаясь к SQL &ndash; Вам предстоит разбить одну большую портянку, на осмысленные гранулярные сценарии. Об этом отдельно можете уточнить у @Mikhail0011, здесь же приведу _почти_ цитату:

Разделите файл с  SQL на количество таблиц, умноженное на два: DDL и DML + 2 (создание базы данных и схемы).

Например, разделение на файлы может быть таким:
  - `01 - DDL - Create database DBLibraryTEST.sql`
  - ~~`02 - DDL - Create schema FilmLabDB.sql`~~ ??
  - `03 - DDL - Create table Authors.sql`
  - ...
  - `09 - DDL - Create table Shelf.sql`
  - `10 - DML - Insert into table Authors.sql`
  - ...
  - `16 - DML - Insert into table Shelf.sql`

**Важно!** Все `*.sql`-скрипты стоит убрать в отдельную папку `scripts`, а исходный код проекта поместить в папку `source`, например.

Также хочу отметить, что _обычно_ таблицы именуются с использованием формы множественного числа существительного (author &rarr; `Authors`, ... shelf &rarr; `Shelves`).

2020-12-15 20:54 UTC, MarinaPaley commented
В таблице `Authors` поле [`MiddleName`](https://github.com/abramson21/ORMLibrary/blob/e47b98428bf7fe0e4a5c92f9d646b6d85aa37ba9/scripts/ScriptDB.sql#L94) стоит сделать `NULL`, так как автор может не иметь отчества.

При ближайшем рассмотрении всех Ваших скриптов на создание таблиц создаётся впечатление, что необходимо переговорить ещё раз о проектировании баз данных. У меня есть опасения, связанные с тем, что плоды вашего труда в области проектирование и реализации базы данных придётся удалить и сделать заново, так как в них имеются фундаментальные ошибки на этапе проектирования. 

Факт ошибочного проектирования схемы базы данных во многом объясняет творчество @dimaalek13. При нормальном проектировании ему не пришлось бы подрисовывать связи в ручную &ndash; они появились бы _автомагически_. Например, такие:

![image](https://user-images.githubusercontent.com/26978698/102271457-7fcc2f00-3f30-11eb-90f1-f9a98c162d89.png)

![image](https://user-images.githubusercontent.com/26978698/102271656-bb66f900-3f30-11eb-9ce2-04a5bf30d48e.png)

Это не эталон, но это делают ваши коллеги из Китая и отечественные студенты из текущей группы ТУУ-411.

2020-12-15 20:54 UTC, MarinaPaley requested changes
В таблице `Authors` поле [`MiddleName`](https://github.com/abramson21/ORMLibrary/blob/e47b98428bf7fe0e4a5c92f9d646b6d85aa37ba9/scripts/ScriptDB.sql#L94) стоит сделать `NULL`, так как автор может не иметь отчества.

При ближайшем рассмотрении всех Ваших скриптов на создание таблиц создаётся впечатление, что необходимо переговорить ещё раз о проектировании баз данных. У меня есть опасения, связанные с тем, что плоды вашего труда в области проектирование и реализации базы данных придётся удалить и сделать заново, так как в них имеются фундаментальные ошибки на этапе проектирования. 

Факт ошибочного проектирования схемы базы данных во многом объясняет творчество @dimaalek13. При нормальном проектировании ему не пришлось бы подрисовывать связи в ручную &ndash; они появились бы _автомагически_. Например, такие:

![image](https://user-images.githubusercontent.com/26978698/102271457-7fcc2f00-3f30-11eb-90f1-f9a98c162d89.png)

![image](https://user-images.githubusercontent.com/26978698/102271656-bb66f900-3f30-11eb-9ce2-04a5bf30d48e.png)

Это не эталон, но это делают ваши коллеги из Китая и отечественные студенты из текущей группы ТУУ-411.

2020-12-21 19:31 UTC, abramson21 commented
Сделана новая БД.

2020-12-21 19:31 UTC, closed without merging