Доделаны все маппинги. Вывод всех книг и таблиц, связанных с ними
abramson21/ORMLibrary pull request #9
Opened 2020-12-09 18:06 UTC by abramson21

Доделаны все маппинги для таблиц, учтены нюансы из #3 , изучение [статьи](https://github.com/nhibernate/fluent-nhibernate/wiki/Getting-started). 

**Результат**:
![image](https://user-images.githubusercontent.com/56224786/101666344-2743f000-3a5f-11eb-83ce-96d1f7bcc5e5.png)

База данных лежит в [ветке](https://github.com/abramson21/ORMLibrary/tree/devSQL_nikolaev).

2020-12-13 21:49 UTC, Const-Phi requested changes
В целом, с учётом замечаний (моих и StyleCop-а) можно мержить. Касательно того, как подружиться со StyleCop &ndash; готов помочь.

P.S. И я бы в веточку под_(реверс)_мерджил свежий мастер. Или отребейзился. Тут уж на вкус и цвет...

![image](https://user-images.githubusercontent.com/8349213/102025078-a3fc0480-3da6-11eb-9b62-12646a40a8d6.png)

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Publication.cs
> +        public virtual string ID_Publication { get; protected set; }
Кажется, что это излишне.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Shelf.cs
> +        public virtual int ID_Room { get; protected set; }
И это тоже излишне.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Author.cs
> +        public override string ToString() => $"{this.Name} ";
Кажется, что пробел здесь попросту забыт.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Book.cs
> +        public virtual string Detailes { get; protected set; }
Всё же [`Details`](https://translate.google.ru/?sl=en&tl=ru&text=details&op=translate&ui=tob).

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Book.cs
> +        public virtual Publication Publication { get; protected set; }
Возможно имелось ввиду `Publisher` или `PublishingHouse`? `Publication` &ndash; издание/публикация.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Genre.cs
> +        public virtual string ID_Book { get; protected set; }
Тоже не очень используется.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Name.cs
> +        public string SecondName { get; }
Может всё же `LastName`? Обычно _second name_ и _middle name_ взаимно исключают одно другое.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Publication.cs
> +        public override string ToString() => $"{this.Name} ";
Кажется, что пробел просто забыт.

2020-12-13 21:49 UTC, Const-Phi commented on Library.NH/Maps/ShelfMap.cs
> +            this.References(x => x.Room).ForeignKey("ID_Room");
Необязательно, так как произойдёт автоматически.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Room.cs
> +        public virtual ISet<Book> Books { get; protected set; } = new HashSet<Book>();
Нужны ли нам книги у комнат? У комнаты есть коллекция полок, у полки есть коллекция книг. Теоретически можно агрегировать по полкам.

2020-12-13 21:49 UTC, Const-Phi commented on TestORMLibrary/stylecop.json
> +  // https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md
С этим могу помочь отдельным коммитом.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Shelf.cs
> +        public virtual int NumberShelf { get; protected set; }
Может быть переименуем в `ShelfNumber` (номер полки, а не полка номера) или просто номер &ndash; `Number`? Последнее существительное &ndash; главное.

2020-12-13 21:49 UTC, Const-Phi commented on Library.Domain/Room.cs
> +        public virtual string Note { get; protected set; }
Не используется при маппинге.

2020-12-15 20:20 UTC, MarinaPaley commented on Infrastructure/Conventions/MyIdConvention.cs
> +        public void Apply(IIdentityInstance instance) => instance.GeneratedBy.Assigned();
С учетом последней лекции, точно ли Assiggned? или выберем другой способ генерировать  Id

2020-12-15 20:34 UTC, MarinaPaley requested changes
Имеет смысл учесть замечания. Возможно, дополнительно переговорить о деталях. После внесения изменений можно мержить.

2020-12-15 20:34 UTC, MarinaPaley commented on Library.Domain/Book.cs
> +        public override string ToString() => $"Название книги: \"{this.Name}\" \n\t Автор: {this.Authors.Join()} \n\t Жанр: {this.Genre} \n\t Детали: {this.Detailes} \n\t Расположение: {this.Room} \n
По большому счёту это больше задача отображения (_view_). Понятно, что на данном этапе нет чёткого структурного разделения на back-protocol-front, так как нет полноценного front-end. Так или иначе стоит обратить внимание на [`Environment.NewLine`](https://docs.microsoft.com/ru-ru/dotnet/api/system.environment.newline?view=net-5.0).

2020-12-15 20:34 UTC, MarinaPaley commented on Library.Domain/Author.cs
> +        public override string ToString() => $"{this.Name} ";
Точно ли тут вообще уместна интерполяция строк? Не проще ли так:
```cs
public override string ToString() => this.Name;
```

2020-12-15 20:34 UTC, MarinaPaley commented on Library.Domain/Publication.cs
> +        public override string ToString() => $"{this.Name} ";
Аналогично и тут.

2020-12-15 20:34 UTC, MarinaPaley commented on Library.Domain/Room.cs
> +        public override string ToString() => $"{this.RoomName} --> Номер полки: {this.Shelves.Join()}";
Эта часть тоже на откуп отсутствующего отображения.

2020-12-21 19:30 UTC, closed without merging